[pytest]
testpaths = testcases
addopts = -v --tb=short --strict-markers

markers =
    smoke: 冒烟测试
    api: API接口测试
    login: 登录相关测试
    regression: 回归测试
    security: 安全测试
    alarm: 告警相关测试
    alarm_disposal: 告警处置
    alarm_notification_template: 告警通知模板
    alarm_rule_crud: 告警规则增删改查
    asset: 资产相关
    asset_hangup_stop: 资产挂起停止
    asset_management: 资产管理
    asset_open_port: 资产开放端口
    asset_patch: 资产补丁
    资产清点_进程列表: 资产清点进程列表
    asset_software: 资产软件
    变更记录: 变更记录
    manage: 管理
    module: 模块
    risk_vulnerability: 风险漏洞
    scenario: 场景测试
    situation_dashboard: 态势大屏
    标签管理: 标签管理
    未知资产搜索: 未知资产搜索

log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)8s] %(name)s: %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S
